<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>stonescript</string>
    <string>stone</string>
    <string>stone.txt</string>
   </array>
  <key>name</key>
  <string>stonescript</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.stonescript</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(//)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.line.double-slash.stonescript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.line.double-slash.stonescript</string>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.stonescript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.block.stonescript</string>
          <key>end</key>
          <string>(^\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.block.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*&gt;.?)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*(\^|:?\?|:(\s+|$)|return(\s+|$)))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#lexpr</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*var(\s+|$))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#lexpr</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*func(\s+|$))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>storage.type.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(^\s*[a-zA-Z]+\s+((?=[^.\+\-\*\x{002f}\x{0025}\x{003d}\(])|$))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=[^\^]))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>ascii</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(ascii\s*$)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.quoted.triple.stonescript</string>
          <key>end</key>
          <string>(^asciiend)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>ascii__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>eolext_pop</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>expr</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>((import|new)(\s+|$))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>string.unquoted.stonescript</string>
          <key>end</key>
          <string>( |$)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.control.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(([Tt]rue|[Ff]alse)(\s+|$))</string>
          <key>name</key>
          <string>constant.language.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((\d+\.?)+)</string>
          <key>name</key>
          <string>constant.numeric.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\x{0021}\x{003d}\+\-\*\+\x{0025}\x{002f}\[\]\(\)\x{002c}\.\|\x{0026}\x{003e}\x{003c}])</string>
          <key>name</key>
          <string>keyword.operator.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(#\w+)</string>
          <key>name</key>
          <string>string.unquoted.stonescript</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#expr__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>string.quoted.double.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#ascii</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((app|loc|foe|item|pickup|harvest|time|totaltime|utc|hp|maxhp|armor|maxarmor|pos|buffs|debuffs|face|ai|bighead|res|player|totalgp|key|screen|rng|rngf|te|draw|input|storage|music|ambient|damage|int|math|vector2|string|Type|ui)(?=[^a-zA-Z0-9_]|$))</string>
          <key>name</key>
          <string>variable.language.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z_][A-Za-z0-9_]*(?=\())</string>
          <key>name</key>
          <string>support.function.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z_][A-Za-z0-9_]*)</string>
          <key>name</key>
          <string>variable.other.stonescript</string>
        </dict>
       </array>
    </dict>
    <key>expr__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>expr__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\\.|[^\x{005c}\x{0022}]+)</string>
          <key>name</key>
          <string>string.quoted.double.stonescript</string>
        </dict>
       </array>
    </dict>
    <key>iexpr</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>lexpr</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#eolext_pop</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#expr</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#eolext_pop</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#eolext_pop</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(@)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.stonescript</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#iexpr</string>
            </dict>
           </array>
          <key>end</key>
          <string>(@)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.character.escape.stonescript</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#ascii</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\x{0040}])</string>
          <key>name</key>
          <string>string.unquoted.stonescript</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#eolext_pop</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z_][A-Za-z0-9_]*(?=\())</string>
          <key>name</key>
          <string>entity.name.function.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\(\)\x{002c}])</string>
          <key>name</key>
          <string>keyword.operator.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([A-Za-z_][A-Za-z0-9_]*)</string>
          <key>name</key>
          <string>variable.parameter.stonescript</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#eolext_pop</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(([Tt]rue|[Ff]alse)(\s+|$))</string>
          <key>name</key>
          <string>constant.language.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([\+\-]*(\d+\.?)+)</string>
          <key>name</key>
          <string>constant.numeric.stonescript</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>variable.parameter.stonescript</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
